-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 15, 2025 at 07:45 AM
-- Server version: 8.0.30
-- PHP Version: 8.3.17

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `docapi_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `db_engines`
--

CREATE TABLE `db_engines` (
  `id` int NOT NULL,
  `engine_name` varchar(50) NOT NULL,
  `default_port` int NOT NULL,
  `describe_syntax` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `db_engines`
--

INSERT INTO `db_engines` (`id`, `engine_name`, `default_port`, `describe_syntax`) VALUES
(1, 'MySQL', 3306, 'DESCRIBE {table_name};'),
(2, 'PostgreSQL', 5432, 'SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns WHERE table_name = \'{table_name}\';'),
(3, 'MSSQL', 1433, 'SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = \'{table_name}\';');

-- --------------------------------------------------------

--
-- Table structure for table `domains`
--

CREATE TABLE `domains` (
  `id` int NOT NULL,
  `url` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `domains`
--

INSERT INTO `domains` (`id`, `url`) VALUES
(4, 'http://localhost:5000/api'),
(5, 'http://localhost:5173/api'),
(1, 'https://contoh.com'),
(6, 'https://esakipnw.apikobar.id'),
(3, 'https://peda.kotawaringinbaratkab.go.id/api'),
(2, 'https://peda.kotawaringinbaratkab.go.id/api/Peserta');

-- --------------------------------------------------------

--
-- Table structure for table `endpoints`
--

CREATE TABLE `endpoints` (
  `id` int NOT NULL,
  `baseUrl` varchar(255) NOT NULL,
  `method` varchar(10) NOT NULL,
  `path` varchar(255) NOT NULL,
  `description` text,
  `status` enum('Develop','Production') DEFAULT 'Develop',
  `websites` text,
  `response` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `endpoints`
--

INSERT INTO `endpoints` (`id`, `baseUrl`, `method`, `path`, `description`, `status`, `websites`, `response`, `created_at`) VALUES
(1, 'https://peda.kotawaringinbaratkab.go.id/api/Peserta', 'GET', '/Contoh3', 'contoh4', 'Production', 'testing', '{\"message\": \"Halo dari server Express!\"}', '2025-08-22 08:19:20'),
(2, 'https://peda.kotawaringinbaratkab.go.id/api/Penguji', 'PUT', '/register1', 'contoh', 'Develop', 'Kementrian', '{\"message\": \"Halo dari server Express!\"}', '2025-08-22 08:30:24'),
(4, 'https://peda.kotawaringinbaratkab.go.id/api/Peserta', 'GET', '/login', 'contoh login', 'Production', 'Kementrian', '{\"message\": \"Halo dari server Express!\"}', '2025-08-27 03:13:08'),
(9, 'https://peda.kotawaringinbaratkab.go.id/api/Peserta', 'GET', '/api', 'Endpoint otomatis untuk proyek API', 'Develop', 'Kementrian', '{\"data\": {\"path\": \"/api\", \"method\": \"GET\", \"project\": \"API\"}, \"message\": \"Contoh response dari proyek API\", \"success\": true}', '2025-09-10 01:41:17'),
(11, 'https://peda.kotawaringinbaratkab.go.id/api', 'GET', '/Peserta', 'hanya contoh', 'Develop', 'mnctv dan antv', '{\"data\": {\"path\": \"/Peserta\", \"method\": \"GET\", \"status\": \"Develop\", \"baseUrl\": \"https://peda.kotawaringinbaratkab.go.id/api\", \"websites\": [\"mnctv dan antv\"], \"description\": \"hanya contoh\"}, \"message\": \"Contoh response dari endpoint\", \"success\": true}', '2025-09-10 04:19:35'),
(14, 'http://localhost:5000/api', 'GET', '/get', 'hanya contoh', 'Develop', 'Kementrian', '{\"data\": {\"path\": \"/get\", \"method\": \"GET\", \"status\": \"Develop\", \"baseUrl\": \"http://localhost:5000/api\", \"websites\": [\"Kementrian\"], \"description\": \"hanya contoh\"}, \"message\": \"Contoh response dari endpoint\", \"success\": true}', '2025-09-10 08:04:56'),
(15, 'https://esakipnw.apikobar.id/data', 'GET', '/tabelSopd', 'hanya contoh', 'Develop', 'Kementrian', '{\"data\": {\"path\": \"/tabelSopd\", \"method\": \"GET\", \"status\": \"Develop\", \"baseUrl\": \"https://esakipnw.apikobar.id\", \"websites\": [\"Kementrian\"], \"description\": \"hanya contoh\"}, \"message\": \"Contoh response dari endpoint\", \"success\": true}', '2025-09-12 02:54:43'),
(17, 'mysql://root@127.0.0.1:3306/docapi_db', 'GET', '/db_engines', 'Autogenerated endpoint for db_engines', 'Production', '', '{\"id\": 1, \"engine_name\": \"MySQL\", \"default_port\": 3306, \"describe_syntax\": \"DESCRIBE {table_name};\"}', '2025-09-15 01:30:09'),
(18, 'mysql://root@127.0.0.1:3306/docapi_db', 'GET', '/domains', 'Autogenerated endpoint for domains', 'Production', '', '{\"id\": 4, \"url\": \"http://localhost:5000/api\"}', '2025-09-15 01:30:09'),
(19, 'mysql://root@127.0.0.1:3306/docapi_db', 'GET', '/endpoints', 'Autogenerated endpoint for endpoints', 'Production', '', '{\"id\": 1, \"path\": \"/Contoh3\", \"method\": \"GET\", \"status\": \"Production\", \"baseUrl\": \"https://peda.kotawaringinbaratkab.go.id/api/Peserta\", \"response\": {\"message\": \"Halo dari server Express!\"}, \"websites\": \"testing\", \"created_at\": \"2025-08-22T08:19:20.000Z\", \"description\": \"contoh4\"}', '2025-09-15 01:30:09'),
(20, 'mysql://root@127.0.0.1:3306/docapi_db', 'GET', '/restapi', 'Autogenerated endpoint for restapi', 'Production', '', '{\"id\": 1, \"ip\": \"127.0.0.1\", \"dsn\": \"postgresql://root@127.0.0.1:5432/apidoc\", \"port\": 5432, \"uuid\": null, \"engine\": \"PostgreSQL\", \"password\": null, \"username\": \"root\", \"projectName\": \"API\", \"database_name\": \"apidoc\"}', '2025-09-15 01:30:09'),
(24, 'http://localhost:5000/api/uuid/fe74b285-d1c0-4bff-a7ff-0de9816a35e7//contoh-project', 'GET', '/restapi', 'Endpoint otomatis untuk proyek Contoh Project', 'Develop', '', '{\"data\": {\"path\": \"/contoh-project\", \"method\": \"GET\", \"project\": \"Contoh Project\"}, \"message\": \"Contoh response dari proyek Contoh Project\", \"success\": true}', '2025-09-15 07:29:52'),
(25, 'http://localhost:5000/api/uuid/725ab404-603b-49d2-92dd-28575950d18e/domains', 'GET', '/domains', 'Endpoint otomatis untuk proyek domains', 'Develop', '', '{\"data\": {\"path\": \"/domains\", \"method\": \"GET\", \"project\": \"domains\"}, \"message\": \"Contoh response dari proyek domains\", \"success\": true}', '2025-09-15 07:35:15');

-- --------------------------------------------------------

--
-- Table structure for table `restapi`
--

CREATE TABLE `restapi` (
  `id` int NOT NULL,
  `uuid` varchar(36) DEFAULT NULL,
  `projectName` varchar(255) NOT NULL,
  `engine` varchar(50) NOT NULL,
  `ip` varchar(50) NOT NULL,
  `port` int NOT NULL DEFAULT '3306',
  `username` varchar(100) NOT NULL,
  `password` varchar(100) DEFAULT NULL,
  `database_name` varchar(100) NOT NULL,
  `dsn` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `restapi`
--

INSERT INTO `restapi` (`id`, `uuid`, `projectName`, `engine`, `ip`, `port`, `username`, `password`, `database_name`, `dsn`) VALUES
(1, NULL, 'API', 'PostgreSQL', '127.0.0.1', 5432, 'root', NULL, 'apidoc', 'postgresql://root@127.0.0.1:5432/apidoc'),
(5, NULL, 'API DATA', 'MySQL', '127.0.0.2', 3306, 'root', NULL, 'apidoc_db', 'mysql://root@127.0.0.2:3306/apidoc_db'),
(6, NULL, 'Trial', 'MySQL', '127.0.0.1', 3306, 'root', NULL, 'docapi_db', 'mysql://root@127.0.0.1:3306/docapi_db'),
(7, 'c8628cee-2d77-4abb-8c73-46a30d7d5ded', 'Doc', 'MySQL', '127.0.0.1', 3306, 'root', NULL, 'docapi_db', 'mysql://root@127.0.0.1:3306/docapi_db'),
(8, 'f0360c3e-8295-4761-bb08-9966e4598735', 'tphp', 'MySQL', '199.0.0.210', 3306, 'root', 'jawara@kominfo123**', 'tphp', 'mysql://root:jawara@kominfo123**@199.0.0.210:3306/tphp'),
(14, '3648d093-d248-42d4-a328-2907f66df421', 'load', 'MySQL', '127.0.0.1', 3306, 'root', '$2b$10$Lq53FwO4ag7nLFfTWU5tm.TT1C0t4LLaKTpF/KEmxslwKU95hztzi', 'docapi_db', 'mysql://root:123buya@127.0.0.1:3306/docapi_db'),
(15, 'e81fa113-7c8d-49f2-9711-b36421b7a8f5', 'tphpenc', 'MySQL', '199.0.0.210', 3306, 'root', '$2b$10$6bc1ba/mWPh2AT1BqjasDu/dljCTEEsthUrp.7OM7xaMxO8.tnzS6', 'tphp', 'mysql://root:jawara@kominfo123**@199.0.0.210:3306/tphp'),
(16, '5ac77084-6351-42f4-844b-de73dfb0948d', 'API DATA', 'MySQL', '127.0.0.1', 3306, 'root', NULL, 'docapi_db', 'mysql://root@127.0.0.1:3306/docapi_db'),
(17, '64424aff-fed2-4576-a224-13af8ff2c97c', 'API', 'MySQL', '127.0.0.1', 3306, 'root', NULL, 'docapi_db', 'mysql://root@127.0.0.1:3306/docapi_db'),
(18, '0e3c19dd-05db-4f67-b8b1-a8b01709fc5f', 'API', 'MySQL', '127.0.0.1', 3306, 'root', NULL, 'docapi_db', 'mysql://root@127.0.0.1:3306/docapi_db'),
(19, 'fe74b285-d1c0-4bff-a7ff-0de9816a35e7', 'Contoh Project', 'MySQL', '127.0.0.1', 3306, 'root', NULL, 'docapi_db', 'mysql://root@127.0.0.1:3306/docapi_db'),
(20, '725ab404-603b-49d2-92dd-28575950d18e', 'domains', 'MySQL', '127.0.0.1', 3306, 'root', NULL, 'docapi_db', 'mysql://root@127.0.0.1:3306/docapi_db');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `db_engines`
--
ALTER TABLE `db_engines`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `domains`
--
ALTER TABLE `domains`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `url` (`url`);

--
-- Indexes for table `endpoints`
--
ALTER TABLE `endpoints`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `restapi`
--
ALTER TABLE `restapi`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `uuid` (`uuid`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `db_engines`
--
ALTER TABLE `db_engines`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `domains`
--
ALTER TABLE `domains`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `endpoints`
--
ALTER TABLE `endpoints`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- AUTO_INCREMENT for table `restapi`
--
ALTER TABLE `restapi`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
